rrdp-iostat: use scanf instead of Str.regexp
xenserver/rrdd-plugins pull request #70
Opened 2021-06-01 12:16 UTC by Wescoeur

Signed-off-by: Pau Ruiz Safont <pau.safont@citrix.com>

2021-06-01 12:42 UTC, lindig approved these changes
Thanks for your submission. This looks good to me. It is good to get rid of `Str` because it is unreliable and `Re` would be a better replacement. Using `scanf` here is fine, too.

2021-06-01 12:46 UTC, lindig commented on src/rrdp-iostat/rrdp_iostat.ml
> +      D.warn {|"%s" returned a line that could not be parsed. Ignoring.\n|} tap_ctl;
These log lines should not have a trailing `\n`

2021-06-01 13:02 UTC, psafont commented
This is a fix for the issue found in https://github.com/xapi-project/blktap/pull/345

This is, state was parsed as a series of decimal digits when it can be a hexadecimal number, and after that the result is ignored.

2021-06-01 13:02 UTC, psafont approved these changes

2021-06-01 14:13 UTC, lindig requested changes
Please remove the `\n` from the log lines.

2021-06-02 10:22 UTC, lippirk commented on src/rrdp-iostat/rrdp_iostat.ml
> +    if not (kind = "vhd" || kind = "aio") then raise (Failure "Unkown type") ;
```suggestion
    if not (kind = "vhd" || kind = "aio") then raise (Failure "Unknown type") ;
```

but this string is never printed, so this is not a problem

2021-06-02 10:22 UTC, lippirk approved these changes

2021-06-02 10:42 UTC, lindig approved these changes

2021-06-02 10:42 UTC, lindig commented
Thanks. Will merge it after the CI did its job.

2021-06-02 10:43 UTC, Wescoeur commented
Nice! Thank you. :)

2021-06-02 12:40 UTC, merged